-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Comments/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE com_comment (
  c_id SERIAL NOT NULL,
  c_page INT NOT NULL,
  c_actor BIGINT DEFAULT 0 NOT NULL,
  c_timestamp TIMESTAMPTZ NOT NULL,
  c_parent INT DEFAULT NULL,
  c_deleted SMALLINT DEFAULT 0 NOT NULL,
  c_rating INT DEFAULT 0 NOT NULL,
  c_html TEXT NOT NULL,
  c_wikitext TEXT NOT NULL,
  c_edited_timestamp TIMESTAMPTZ DEFAULT NULL,
  PRIMARY KEY(c_id)
);

CREATE INDEX c_timestamp ON com_comment (c_timestamp);

CREATE INDEX c_page_timestamp ON com_comment (c_page, c_timestamp);

CREATE INDEX c_actor_timestamp ON com_comment (c_actor, c_timestamp);


CREATE TABLE com_rating (
  cr_comment INT NOT NULL,
  cr_actor BIGINT DEFAULT 0 NOT NULL,
  cr_rating INT NOT NULL,
  PRIMARY KEY(cr_comment, cr_actor)
);
