-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Comments/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/com_comment (
  c_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  c_page INTEGER UNSIGNED NOT NULL, c_actor BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  c_timestamp BLOB NOT NULL, c_parent INTEGER UNSIGNED DEFAULT NULL,
  c_deleted_actor BIGINT UNSIGNED DEFAULT NULL,
  c_rating INTEGER DEFAULT 0 NOT NULL,
  c_html BLOB NOT NULL, c_wikitext BLOB NOT NULL,
  c_edited_timestamp BLOB DEFAULT NULL
);

CREATE INDEX c_timestamp ON /*_*/com_comment (c_timestamp);

CREATE INDEX c_parent ON /*_*/com_comment (c_parent);

CREATE INDEX c_page_timestamp ON /*_*/com_comment (c_page, c_timestamp);

CREATE INDEX c_actor_timestamp ON /*_*/com_comment (c_actor, c_timestamp);


CREATE TABLE /*_*/com_rating (
  cr_comment INTEGER UNSIGNED NOT NULL,
  cr_actor BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  cr_rating INTEGER NOT NULL,
  PRIMARY KEY(cr_comment, cr_actor)
);
