-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/Comments/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/com_comment (
  c_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  c_page INT UNSIGNED NOT NULL,
  c_actor BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  c_timestamp BINARY(14) NOT NULL,
  c_parent INT UNSIGNED DEFAULT NULL,
  c_deleted TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  c_rating INT DEFAULT 0 NOT NULL,
  c_html MEDIUMBLOB NOT NULL,
  c_wikitext MEDIUMBLOB NOT NULL,
  c_edited_timestamp BINARY(14) DEFAULT NULL,
  INDEX c_timestamp (c_timestamp),
  INDEX c_parent (c_parent),
  INDEX c_page_timestamp (c_page, c_timestamp),
  INDEX c_actor_timestamp (c_actor, c_timestamp),
  PRIMARY KEY(c_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/com_rating (
  cr_comment INT UNSIGNED NOT NULL,
  cr_actor BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  cr_rating INT NOT NULL,
  PRIMARY KEY(cr_comment, cr_actor)
) /*$wgDBTableOptions*/;
